import type {
  HomeCarouselFilter,
  HomeCarouselProduct,
} from "@/types/home-carousel";

const publicAsset = (path: string) => `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}${path}`;

export const homeCarouselFilters: HomeCarouselFilter[] = [
  { label: "Steam Wallet", value: "steam-wallet" },
  { label: "ChatGPT", value: "chatgpt" },
  { label: "CS2", value: "cs2" },
  { label: "CS:GO", value: "csgo" },
  { label: "Dota 2", value: "dota2" },
  { label: "Rust", value: "rust" },
];

export const homeCarouselProducts: HomeCarouselProduct[] = [
  {
    accent: "#90f6d9",
    badge: "ggsel",
    category: "steam-wallet",
    categoryLabel: "Steam Wallet",
    description: "Валюта. 1 Points = 0.02 ₽. Автовыдача 24/7.",
    id: "steam-points-autodelivery",
    imageAlt: "Steam Поинты | АВТО ДОСТАВКА 24/7 | Комиссия",
    name: "Steam Поинты",
    price: "1 Points = 0.02 ₽",
    source: "ggsel",
    sourceUrl: "https://ggsel.net/catalog/steam",
    stat: "18 950 продаж",
    visualCode: "SW",
  },
  {
    accent: "#74d8ff",
    badge: "ggsel",
    category: "steam-wallet",
    categoryLabel: "Steam Wallet",
    description: "Аккаунт. Регион Казахстан. Цена указана в карточке до покупки.",
    id: "steam-kazakhstan-account",
    imageAlt: "КАЗАХСКИЙ АККАУНТ СТИМ/STEAM(Регион Казахстан)",
    name: "КАЗАХСКИЙ АККАУНТ СТИМ",
    price: "99 ₽",
    source: "ggsel",
    sourceUrl: "https://ggsel.net/catalog/steam",
    stat: "100+ продаж",
    visualCode: "KZ",
  },
  {
    accent: "#d7c8a4",
    badge: "ggsel",
    category: "steam-wallet",
    categoryLabel: "Steam Wallet",
    description: "Услуга. Смена региона Steam на Казахстан.",
    id: "steam-region-kazakhstan",
    imageAlt: "СМЕНА РЕГИОНА СТИМ КАЗАХСТАН",
    name: "СМЕНА РЕГИОНА СТИМ КАЗАХСТАН",
    price: "229 ₽",
    source: "ggsel",
    sourceUrl: "https://ggsel.net/catalog/steam",
    stat: "1 000+ продаж",
    visualCode: "KZT",
  },
  {
    accent: "#d7c8a4",
    badge: "ggsel",
    category: "chatgpt",
    categoryLabel: "ChatGPT",
    description: "Аккаунт. ChatGPT Plus AI на 30 дней.",
    id: "chatgpt-plus-ai-30",
    imageAlt: "Чат GPT Plus AI 30 дней",
    name: "Чат GPT Plus AI 30 дней",
    price: "749 ₽",
    source: "ggsel",
    sourceUrl: "https://ggsel.net/catalog/chatgpt-plus",
    stat: "62 продажи",
    visualCode: "GPT",
  },
  {
    accent: "#90f6d9",
    badge: "ggsel",
    category: "chatgpt",
    categoryLabel: "ChatGPT",
    description: "Аккаунт. Общий аккаунт на 1 месяц.",
    id: "chatgpt-plus-global",
    imageAlt: "ChatGPT Plus 1 месяц — общий аккаунт (глобальный)",
    name: "ChatGPT Plus 1 месяц",
    price: "799 ₽",
    source: "ggsel",
    sourceUrl: "https://ggsel.net/catalog/chatgpt-plus",
    stat: "26 продаж",
    visualCode: "AI",
  },
  {
    accent: "#b78cff",
    badge: "ggsel",
    category: "chatgpt",
    categoryLabel: "ChatGPT",
    description: "Покупка подписки. Автоматическая выдача 24/7.",
    id: "chatgpt-plus-auto",
    imageAlt: "24/7 АВТО ЧатГПТ 5.5 PLUS / 1 Месяц",
    name: "24/7 АВТО ЧатГПТ 5.5 PLUS",
    price: "2 399 ₽",
    source: "ggsel",
    sourceUrl: "https://ggsel.net/catalog/chatgpt-plus",
    stat: "471 продажа",
    visualCode: "5.5",
  },
  {
    accent: "#f26a2e",
    badge: "LIS-SKINS",
    category: "cs2",
    categoryLabel: "CS2",
    description: "FN / 0.062128. Доставка до 12 часов.",
    id: "cs2-ak47-wild-lotus-fn",
    imageAlt: "AK-47 | Wild Lotus (Factory New)",
    imageUrl: publicAsset("/assets/products/ak47-wild-lotus.png"),
    name: "AK-47 | Wild Lotus",
    price: "13 448.07 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/cs2/",
    stat: "Factory New",
    visualCode: "AK",
  },
  {
    accent: "#ff6b5c",
    badge: "LIS-SKINS",
    category: "cs2",
    categoryLabel: "CS2",
    description: "ST™ / FN / 0.031994. В наличии несколько предметов.",
    id: "cs2-butterfly-doppler-ruby",
    imageAlt: "StatTrak™ ★ Butterfly Knife | Doppler Ruby (Factory New)",
    imageUrl: publicAsset("/assets/products/butterfly-doppler.png"),
    name: "StatTrak™ ★ Butterfly Knife | Doppler Ruby",
    price: "13 410.06 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/cs2/",
    stat: "Factory New",
    visualCode: "BF",
  },
  {
    accent: "#75a7ff",
    badge: "CS.MONEY",
    category: "cs2",
    categoryLabel: "CS2",
    description: "Sv / FN / 0.0276. На витрине CS.MONEY.",
    id: "cs2-awp-dragon-lore",
    imageAlt: "AWP | Dragon Lore",
    imageUrl: publicAsset("/assets/products/awp-dragon-lore.png"),
    name: "AWP | Dragon Lore",
    price: "45 834.28 zł",
    source: "CS.MONEY",
    sourceUrl: "https://cs.money/ru/market/buy/",
    stat: "Factory New",
    visualCode: "AWP",
  },
  {
    accent: "#f26a2e",
    badge: "LIS-SKINS",
    category: "csgo",
    categoryLabel: "CS:GO",
    description: "FN / 0.062128. Цена из раздела КС ГО.",
    id: "csgo-ak47-wild-lotus-fn",
    imageAlt: "AK-47 | Wild Lotus (Factory New)",
    imageUrl: publicAsset("/assets/products/ak47-wild-lotus.png"),
    name: "AK-47 | Wild Lotus",
    price: "13 448.07 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/csgo/",
    stat: "Factory New",
    visualCode: "AK",
  },
  {
    accent: "#d7c8a4",
    badge: "LIS-SKINS",
    category: "csgo",
    categoryLabel: "CS:GO",
    description: "FN / 0.069982. Доставка до 12 часов.",
    id: "csgo-awp-gungnir-fn",
    imageAlt: "AWP | Gungnir (Factory New)",
    imageUrl: publicAsset("/assets/products/awp-gungnir.png"),
    name: "AWP | Gungnir",
    price: "11 401.55 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/csgo/",
    stat: "Factory New",
    visualCode: "GN",
  },
  {
    accent: "#ff635c",
    badge: "LIS-SKINS",
    category: "csgo",
    categoryLabel: "CS:GO",
    description: "ST™ / FN / 0.059879. Редкая позиция.",
    id: "csgo-m4a4-howl-fn",
    imageAlt: "StatTrak™ M4A4 | Howl (Factory New)",
    imageUrl: publicAsset("/assets/products/m4a4-howl.png"),
    name: "StatTrak™ M4A4 | Howl",
    price: "11 894.76 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/csgo/",
    stat: "Factory New",
    visualCode: "M4",
  },
  {
    accent: "#b78cff",
    badge: "LIS-SKINS",
    category: "dota2",
    categoryLabel: "Dota 2",
    description: "Позиция из каталога Dota 2. Скидка -38%.",
    id: "dota-genuine-axe-phractos",
    imageAlt: "Genuine Axe of Phractos",
    name: "Genuine Axe of Phractos",
    price: "387.77 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/dota2/",
    stat: "-38%",
    visualCode: "AXE",
  },
  {
    accent: "#ff9d5c",
    badge: "LIS-SKINS",
    category: "dota2",
    categoryLabel: "Dota 2",
    description: "Crimson Witness. Скидка -7%.",
    id: "dota-eyes-ardenok",
    imageAlt: "Eyes of Ardenok of the Crimson Witness",
    name: "Eyes of Ardenok of the Crimson Witness",
    price: "350.07 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/dota2/",
    stat: "-7%",
    visualCode: "CW",
  },
  {
    accent: "#90f6d9",
    badge: "LIS-SKINS",
    category: "dota2",
    categoryLabel: "Dota 2",
    description: "Immortal-предмет. Позиция из верхней выдачи.",
    id: "dota-mace-aeons",
    imageAlt: "Mace of Aeons",
    name: "Mace of Aeons",
    price: "222.98 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/dota2/",
    stat: "-17%",
    visualCode: "MA",
  },
  {
    accent: "#ff9d5c",
    badge: "LIS-SKINS",
    category: "rust",
    categoryLabel: "Rust",
    description: "Раздел Rust. Популярная позиция из верхней выдачи.",
    id: "rust-big-grin",
    imageAlt: "Big Grin",
    imageUrl: publicAsset("/assets/products/rust-big-grin.png"),
    name: "Big Grin",
    price: "800.57 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/rust/",
    stat: "-26%",
    visualCode: "BG",
  },
  {
    accent: "#f26a2e",
    badge: "LIS-SKINS",
    category: "rust",
    categoryLabel: "Rust",
    description: "Одежда. Скидка -30%.",
    id: "rust-fire-jacket",
    imageAlt: "Fire jacket",
    imageUrl: publicAsset("/assets/products/rust-fire-jacket.png"),
    name: "Fire jacket",
    price: "398.67 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/rust/",
    stat: "-30%",
    visualCode: "FJ",
  },
  {
    accent: "#90f6d9",
    badge: "LIS-SKINS",
    category: "rust",
    categoryLabel: "Rust",
    description: "Оружие. В карточке указано x4.",
    id: "rust-tempered-mp5",
    imageAlt: "Tempered Mp5",
    imageUrl: publicAsset("/assets/products/rust-tempered-mp5.png"),
    name: "Tempered Mp5",
    price: "336.70 €",
    source: "LIS-SKINS",
    sourceUrl: "https://lis-skins.com/ru/market/rust/",
    stat: "x4",
    visualCode: "MP5",
  },
];
